#!/usr/bin/env bash

function set_colors
{
    bold=$'\e[1m'
    reset=$'\e[0m'
    uline=$'\e[4m'

    for i in {0..7}; do
        f+=("$(printf "%b" "\\e[3${i}m")")
        b+=("$(printf "%b" "\\e[4${i}m")")
        fb+=("${f[$i]}${bold}")
        bb+=("${b[$i]}${bold}")
    done

    tick="[${f[2]}✔${reset}]"
    cross="[${f[1]}✗${reset}]"
}

function unset_colors
{
    unset bold reset uline
    unset {f,b}{,b}

    tick="[✔]"
    cross="[✗]"
}

function get_full_path
(
    target="$1"

    if [[ -f "${target}" ]]; then
        filename="${target##*/}"
        [[ "${filename}" == "${target}" ]] && \
            target="./${target}"
        target="${target%/*}"
        cd "${target}" || exit
        full_path="${PWD}"
    elif [[ -d "${target}" ]]; then
        cd "${target}" || exit
        full_path="${PWD}"
    fi

    printf "%s" "${full_path}"
)

function bar
(
    ((elapsed = ($1 * $2 / 100)))
    printf -v progress "%${elapsed}s"
    printf -v total "%$(($2 - elapsed))s"
    printf "%s" "[${progress// /\#}${total}]"
)

function check_app
{
    ((BASH_VERSINFO[0] < 4 || BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 4)) && {
        printf "%s\\n" "Bash 4.4+ required"
        _exit="true"
    }

    app_list=("ffmpeg")

    for i in "${app_list[@]}"; do
        ! type -p ${i} > /dev/null && \
            missing+=("${i}")
    done

    ((${#missing[@]} > 0)) && {
        _exit="${exit:=true}"
        for i in "${missing[@]}"; do
            printf "%s\\n" "${i} is not installed"
        done
    }

    [[ "${_exit}" == "true" ]] && {
        printf "%s\\n" "Exiting..."
        exit 1
    }
}

function check_dirs
{
    input_dir_cache="${input_dir%/}"
    output_dir_cache="${output_dir%/}"

    input_dir="$(get_full_path "${input_dir_cache}")"
    if [[ ! "${output_dir}" ]]; then
        output_dir="${PWD}/out"
    else
        output_dir="$(get_full_path "${output_dir_cache}")"
    fi

    [[ ! -d "${input_dir}" ]] && {
        print_usage
        if [[ ! "${input_dir}" ]]; then
            printf "%s\\n" "Input directory does not exist"
        else
            printf "%s\\n" "\"${input_dir}\" is not a valid input directory"
        fi
        printf "%s\\n\\n" "Exiting..."
        exit 1
    }

    [[ ! -d "${output_dir}" ]] && {
        if [[ ! "${input_dir}" ]]; then
            printf "%s\\n" "Output directory does not exist"
        else
            printf "%s\\n" "\"${output_dir}\" is not a valid output directory"
        fi
        printf "%s\\n" "Do you want to create it? [${f[2]}Y${reset}/${f[1]}n${reset}] "
        read -r a
        if [[ ! "${a}" || "${a}" =~ ^[Yy]$ ]]; then
            mkdir -p "${output_dir_cache}"
            output_dir="$(get_full_path "${output_dir_cache}")"
        else
            printf "%s\\n\\n" "Exiting..."
            exit 1
        fi
    }
}

function print_usage
{
    printf "%s\\n" "
Usage:  $0 --option --option \"${uline}${bold}VALUE${reset}\"

    Options:

    [-i|--input \"${uline}${bold}DIRECTORY${reset}\"]        Input path for files
    [-o|--output \"${uline}${bold}DIRECTORY${reset}\"]       Output path for converted files
    [-j|--parallel \"${uline}${bold}INT${reset}\"]           Perform conversion in parallel
    [-q|--quiet]                    Suppress all messages
    [-w|--overwrite]                Overwrite converted files
    [-m|--merge]                    Copy incompatible files to
                                    the output directory

    [--no-colors]                   Disable color output
    [--ffmpeg-flags \"${uline}${bold}FLAGS${reset}\"]        Set flags for ffmpeg 
                                    DEFAULT: \"-q:a 0 -loglevel fatal\"

    [-h|--help]                     Print this message
"
}

function get_args
{
    [[ ! "$1" ]] && {
        print_usage
        printf "%s\\n\\n" "No arguments passed"
        exit 1
    }


    while (($# > 0)); do
        case "$1" in
            "-i"|"--input")     input_dir="$2"; shift ;;
            "-o"|"--output")    output_dir="$2"; shift ;;
            "-j"|"--parallel")  ((parallel > 0)) && parallel="$2"; shift ;;
            "-q"|"--quiet")     [[ "${-}" != *"x"* ]] && exec > /dev/null 2>&1 ;;
            "-w"|"--overwrite") overwrite="true" ;;
            "-m"|"--merge")     merge="true" ;;
            "-h"|"--help")      print_usage; exit 0 ;;
            "--ffmpeg-flags")   ffmpeg_flags="$2"; shift ;;
            "--no-colors")      unset_colors ;;
        esac
        shift
    done
}

function get_file_list
{
    shopt -s globstar
    for file in "${input_dir}"/**/*; do
        [[ ! -d "${file}" ]] && {
            local file_ext="${file##*.}"
            if [[ "${file_ext,,}" =~ ^(wav|flac)$ ]]; then
                file_list+=("${file}")
            elif [[ "${merge}" == "true" ]]; then
                incompatible+=("${file}")
            fi
        }
    done
    shopt -u globstar
}

function display_merge_progress
{
    str="(${count:=1}/${#incompatible[@]}) Merging files "
    shopt -s checkwinsize; (:;:)
    awk_script='BEGIN {printf "%0.0f", (a / b) * 100}'
    percent="$(awk -v a="${count}" -v b="${#incompatible[@]}" "${awk_script}")"
    cols="$((COLUMNS - (${#str} + 2)))"
    bar_str="$(bar "${percent}" "${cols}")"
    str+="${bar_str}"
    ((count++))
    printf "%s\\r" "${str}"
}

function merge_files
(
    [[ "${merge}" != "true" ]] && return

    for file in "${incompatible[@]}"; do
        display_merge_progress
        source_dir="${file%/*}"
        source_dir="${source_dir#${input_dir}}"
        source_file="${file##*/}"
        output_source_dir="${output_dir}${source_dir}"
        output_filename="${output_source_dir}/${source_file}"
        mkdir -p "${output_source_dir}"
        cp "${file}" "${output_filename}"
    done
    printf "\\n"
)

function process_files
(
    function _process
    (
        trap "exit 1" INT
        ffmpeg_flags="${ffmpeg_flags:=-q:a 0 -loglevel fatal}"
        for file in "$@"; do
            source_dir="${file%/*}"
            source_dir="${source_dir#${input_dir}}"
            source_file="${file##*/}"
            source_filename="${source_file%.*}"
            output_source_dir="${output_dir}${source_dir}"
            output_filename="${output_source_dir}/${source_filename}.mp3"
            display="${file#${input_dir}}"
            display="${display#/}"

            mkdir -p "${output_source_dir}"

            [[ "${overwrite}" == "true" && -f "${output_filename}" ]] && \
                rm "${output_filename}"

            printf "%s\\r" "${display}"
            if ffmpeg -i "${file}" ${ffmpeg_flags} "${output_filename}"; then
                printf "%s\\n" "${tick} ${display%.*}.mp3"
            else
                printf "%s\\n" "${cross} ${display%.*}.mp3"
            fi
        done
    )

    if [[ "${parallel}" ]] && ((parallel != 1)); then
        old_ifs="${IFS}"
        split="$((${#file_list[@]} / ${parallel}))"
        for ((i = 0; i < parallel - 1; i++)); do
            IFS="," group[$i]="${file_list[*]:${a:-0}:${split}}"
            ((a+=split))
        done
        IFS="," group["$((parallel - 1))"]="${file_list[*]:${a:-0}}"
        IFS="${old_ifs}"

        for ((i = 0; i < parallel; i++)); do
            mapfile -d "," -t temp_arr < <(printf "%s" "${group[$i]}")
            _process "${temp_arr[@]}" &
        done
        wait
    else
        _process "${file_list[@]}"
    fi
)

function display_seconds
(
    secs="${SECONDS}"
    hours="$((secs / 60 / 60 % 24))"
    mins="$((secs / 60 % 60))"
    secs="$((secs - ((mins * 60) + (hours * 3600))))"

    hours+="h "
    mins+="m "
    secs+="s"

    ((${hours/h*} == 0)) && unset hours
    ((${mins/m*} == 0)) && unset mins

    printf "%s\\n" "Converted ${#file_list[@]} files in ${hours:-}${mins:-}${secs}"
)

function main
{
    set_colors
    get_args "$@"
    check_app
    check_dirs

    get_file_list
    merge_files
    if process_files; then
        display_seconds
    else
        printf "%s\\n" "" "Interrupted" "Exiting..." ""
    fi
}

main "$@"
